### PR TITLE
Japanese translation 2021

### PR DESCRIPTION
**Pull request by NurseAngel**
Add Japanese translation rising star 2021.

### CODE REVIEW

**Comment by michaelrambeau** [comment]
Hello @NurseAngel thank you very much for your hard work!

- Could you merge `develop` branch into your feature branch because I updated `public/img/2021/en/rising-stars.png` image (see #92 )? This is why there is a conflict. 
- Could you translate the new items in https://github.com/bestofjs/javascript-risingstars/blob/develop/i18n/messages/common/ja.json
 
```json
"trends": "Trends in {year}",
"data": "GitHub data",
"stars_total": "Total stars",
"links": "Links"
```

Thank you in advance!

**Comment by NurseAngel** [comment]
Hi!

- merged rising-stars.png and resolve conflict.
- translate common/ja.json.

**Comment by michaelrambeau** [comment]
Thank you very much @NurseAngel !
I'm merging.
By the way do you want to join us on Discord? I can speak Japanese 😄 
https://discord.gg/HxbNRkvD

**Comment by NurseAngel** [comment]
Thanks!
but, sorry I'm not using Discord.

**Comment by NurseAngel** [comment]
> Thank you very much @NurseAngel ! I'm merging. By the way do you want to join us on Discord? I can speak Japanese 😄 https://discord.gg/HxbNRkvD

Thanks!
but, sorry I'm not using Discord.

**Comment by michaelrambeau** [comment]
@NurseAngel  OK, I understand.
We have a Slack team too, do you want me to invite you?
Send me your email by direct message in Twitter for example if you are interested, see you there!

**Pull request merged**
