### PR TITLE
korean translate 2021

### PR DESCRIPTION
**Pull request by rewrite0w0**
Add korean translation javascript rising star 2021

modify files
allLanguages.json
settings.json

and sorry.
I added korean infomation at will because I thought it was first time for korean translate.

### CODE REVIEW

**Review by michaelrambeau — APPROVED** [review]
Thank you very much @rewrite0w0 !
The Korean edition will be online very soon.

**Review by michaelrambeau — CHANGES_REQUESTED** [review]
Just one thing @rewrite0w0 : could you discard the changes to `package.lock` file?

I guess the file was updated because of a different version of Node.js.

**Comment by rewrite0w0** [comment]
oh, I didn't notice.
I deleted the file :)

**Comment by michaelrambeau** [comment]
@rewrite0w0 it seems you deleted the file `package-lock`file this time 🗑️  😄 

You don't have to delete it: you have to discard the changes you made, so that the file does not appears in the list of "File changed" in this Pull Request, do you know what I mean, could you do it?

Thank you in advance!

**Comment by rewrite0w0** [comment]
I deleted my file... then copied file from the original repo. I wonder if it'll be solved like this...?
and thanks for advice :)

**Comment by rewrite0w0** [comment]
I'm curious if there's any other way.
git checkout --file,
git fetch original repo
I tried these two methods, but it didn't move I thought. sorry.
if you fine, please can you teach me how to turn it back neatly...?

**Review by michaelrambeau — APPROVED** [review]
👍 Thank you very much, I'm going to release everything.

I will add a commit to display your avatar at the bottom of the page, like we do for all translated versions.

**Comment by michaelrambeau** [comment]
> if you fine, please can you teach me how to turn it back neatly...?

@rewrite0w0  I think you can do that:

```shell
 git checkout origin/master package-lock.json
```

and then make a new commit.

**Comment by rewrite0w0** [comment]
thanks for teach :)
that was the right way.
I didn't think about "git checkout from original"
but i noticed that now.

**Comment by michaelrambeau** [comment]
@rewrite0w0 I'm adding your name, avatar and short bio at the bottom of the page.

What do you want to be displayed below your name, as your short bio?
I can change your name on the screen if you prefer.


image

**Comment by rewrite0w0** [comment]
name : Oh TaeJun
bio: hello :)

please :)

**Comment by michaelrambeau** [comment]
> name : Oh TaeJun bio: hello :)

Oh really, you don't want to be famous, you don't want to tell the world who you are? The world is watching! 🌐 😄 

It would look like this:

image

OK like this?

**Comment by rewrite0w0** [comment]
my thought was rewrite0w0(oh taejun)
if you feeling so long... just rewrite0w0 please
and my bio is hello :) please
i love smile :)

**Comment by michaelrambeau** [comment]
No problem, anything is possible!

Like this?

image

**Comment by rewrite0w0** [comment]
oh sorry,
oh taejun (rewrite0w0)
please Then I think it's completed.
thanks :)

**Comment by michaelrambeau** [comment]
Is it OK to capitalize like this? (to be consisted with other language versions)

image

**Comment by rewrite0w0** [comment]
If you capitalize **j**, it's perfect :D

**Comment by michaelrambeau** [comment]
Just to be 100%, like this? 😅 

```
Oh TaeJun (rewrite0w0)
Hello :)
```

**Comment by rewrite0w0** [comment]
yeah, perfect :)

**Comment by michaelrambeau** [comment]
@rewrite0w0 it's live, please check the result!

https://risingstars.js.org/2021/ko

**Pull request merged**
