### PR TITLE
Zh | update Chinese version (and some code...)

### PR DESCRIPTION
**Pull request by seognil**
* MERGE from master

* UPDATE Chinese version text
* ADD me as translator in teamMembers
* ADD readme description (my yarn problem)

* FIX SSG description error: vuepress and nuxt is at 3 & 4

**!!! breaking change !!!**(the latest commit)
* UPDATE sort existed teamMembers by time order (change the data structure)
(well just my favor)
(in case of someone made multi translation?...)

### CODE REVIEW

**Comment by michaelrambeau** [comment]
Hello @seognil 
Thank you very much for your hard work.
You should be mentioned as a the translator of the 2018 edition, you are perfectly right.

About your PR, the fact that you re-used a previous branch annoys me, it makes the `diff`difficult to understand, even if I understand it's only the result of the `merge` process.

So I have just updated the `dev` branch, adding you as a team member, as you see here: 

https://dev--risingstars.netlify.com/2018/zh/

image

If you don't mind, could you add the corrections you mention about the SSG part and the Yarn problem, creating a new branch from `dev`?

Thank you for your understanding, sorry for the inconvenience!

**Comment by seognil** [comment]
@michaelrambeau 
ok I'll check that later
(not much experience for open source project working process, bear with me :)

BTW, a translation problem.
I'm not sure that what's the mean of `archival` from `TypeScript, from Microsoft took a big advantage over its archival Flow`
Does that mean `TS is inspired by Flow` or `Flow is TS's predecessor`?

**Comment by michaelrambeau** [comment]
@seognil it was a typo in the English version, sorry, I wanted to write "arch-rival", I wanted to say that "Flow is the biggest rival of TypeScript".

**Comment by seognil** [comment]
@michaelrambeau 
so found a bug LOL

**Comment by michaelrambeau** [comment]
@seognil Thank you for having found the bug! 😄 

And sorry for having closed your PR, it would be great if you open an other one with the changes you did in the Chinese translations.

FYI I will try to solve the NPM package version problem before the next edition, upgrading Gatsby and getting rid of Sass, I think.

**Pull request closed without merging**
