### PR TITLE
Translate 2017 version to Bahasa Indonesia

### PR DESCRIPTION
**Pull request by lobothijau**

### CODE REVIEW

**Comment by lobothijau** [comment]
Is there anything I should finish before doing this PR?

**Comment by michaelrambeau** [comment]
Hello @lobothijau 
Thank you for the translations and sorry for the late reply.
I'm adjusting the layout so that the language menu fits the mobile screens, I will let you know when it's ready.

**Comment by michaelrambeau** [comment]
Hello @lobothijau 
I merged the Indonesian version into the `dev` branch.
Could you check the result here: https://risingstars-dev.netlify.com/ (it's a temporary URL for tests only)?

**Comment by lobothijau** [comment]
Hello @michaelrambeau 
Thank you for your help. I have checked the result and it looks perfect for me unless there are some mistakes I found (some typos and punctuation). Can I update them and create a new PR after this PR is merged or should I just revise this PR?

**Comment by michaelrambeau** [comment]
Hello @lobothijau,
Could you make a new PR because I have already merged everything into the master branch?
Thank you!

**Comment by lobothijau** [comment]
Sure, I will do a new PR for them. 
Thank you for your assistance.

**Pull request merged**
