### PR TITLE
Ja translation 2020

### PR DESCRIPTION
**Pull request by NurseAngel**
Add Japanese traslation.

### CODE REVIEW

**Comment by michaelrambeau** [comment]
👍 @NurseAngel Thank you very much for the translations!

**Comment by michaelrambeau** [comment]
@NurseAngel is it OK if we had your name at the end of the page, like this?

Do you want something to be displayed for your bio?

image

**Comment by NurseAngel** [comment]
OK,Thanks!!

bio plz
"Houkago Atelier Toiro ha iizo."

**Comment by michaelrambeau** [comment]
Done @NurseAngel please check again https://risingstars.js.org/2020/ja

Your name has beed added to the README.md too.

Thank you for checking!

**Pull request merged**
