### PR TITLE
feat: Chinese translation 2023

### PR DESCRIPTION
**Pull request by poozhu**

### CODE REVIEW

**Review by michaelrambeau — APPROVED** [review]
Thank you very much @poozhu 🚀 🇨🇳

**Comment by michaelrambeau** [comment]
It's live! https://risingstars.js.org/2023/zh

**Comment by poozhu** [comment]
> Thank you very much @poozhu 🚀 🇨🇳 

my pleasure :)

**Comment by poozhu** [comment]
> Thank you very much @poozhu 🚀 🇨🇳 

my pleasure ✌️

**Pull request merged**
